[workspace]

members = [
    "voidray-core",
    "voidray-math",
]

[profile.release]
lto = "thin"
incremental = true
debug = true

[profile.opt]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = "debuginfo"
opt-level = 3
